### ISSUE TITLE
Investigate potential overflows in the complex demosaicing definitions.

### ISSUE THREAD

**Issue by m0ose** [colour-science/colour-demosaicing#1]
I am using this with a point grey camera, and I get some weird artifacts while using the demosaicing_CFA_Bayer_DDFAPD, demosaicing_CFA_Bayer_Malvar2004, and demosaicing_CFA_Bayer_Menon2007 methods.
The method demosaicing_CFA_Bayer_bilinear doesn't seem to have that problem. 

They look like these blue dots. I am thinking that the colors are overflowing the byte. 
![screen shot 2016-10-05 at 12 57 01 pm](https://cloud.githubusercontent.com/assets/393666/19127194/449b8bee-8afb-11e6-8a4e-4901936e910b.png)

**Comment by KelSolaar** [comment]
Hi,

It might be hard to debug without more information, do you have the file to test?

**Comment by m0ose** [comment]
I found a workaround. It turns out the input data was in uint8 and stringIO was expecting values between 0 and 255. The demosaicing algorithm produced several values that were bigger than 255, which I think got converted into zeros somewhere(probably in stringIO). 
 
```
    # This is a way to output a good demosaiced uint8, from uint8 input
    m = m.astype('float32')
    m = colour_demosaicing.demosaicing_CFA_Bayer_Menon2007(m)
    print 'negative count:', (m < 0).sum(), ', bigger than 255: ' , (m > 255).sum()
    m = m.clip(0,255)
    m = m.astype('uint8')
```

Here is a test image, if you are still interested. 
![shot_bayer](https://cloud.githubusercontent.com/assets/393666/19160100/d86739e4-8bab-11e6-8c86-46f1b0017efe.png)

and the messed up version:
![shot_problem](https://cloud.githubusercontent.com/assets/393666/19160668/fa96c442-8bad-11e6-9c89-17ec89ca7cd6.png)

**Comment by KelSolaar** [comment]
Hi,

I was suspecting something along those lines!

Please be aware that the algorithms were tested with floating point images in [0, 1] domain, not integer [0, 255], integer [0, 65535] or any integer representation. You might want to divide your input to the functions by `bit_depth - 1`.
