### ISSUE TITLE
color shift at white space for Malvar04

### ISSUE THREAD

**Issue by GuoShi28** [colour-science/colour-demosaicing#11]
Hi,
   I met a problem that using  Malvar04 can not convert white space correctly.
![image](https://user-images.githubusercontent.com/19340458/53570079-97da8f00-3ba0-11e9-9b78-c6fcf197b283.png).
  The left image is the originally space image, the middle image is the bayer image, the right is the output of the Malvar04. Can you help me to solve this problem?
  Also, the result of the bluid-in code in matlab works fine. Matlab results:
![image](https://user-images.githubusercontent.com/19340458/53570257-03246100-3ba1-11e9-9b44-fc02d0f1cdec.png)
To note that, the bayer images are the same in matlab and python.

**Comment by GuoShi28** [comment]
Sorry!, It's my fault. The code works fine. Thank you for sharing.

**Comment by KelSolaar** [comment]
No worries! :)
