### ISSUE TITLE
Git fatal message upon import.

### ISSUE THREAD

**Issue by jewfro-cuban** [colour-science/colour-demosaicing#12]
Getting the following message upon importing:

fatal: Not a git repository (or any of the parent directories): .git

Started ~ a month ago.

**Comment by KelSolaar** [comment]
@jewfro-cuban : Thanks! This is hopefully not affecting the package or import itself [as all the exceptions are caught where this happens](https://github.com/colour-science/colour-demosaicing/blob/develop/colour_demosaicing/__init__.py#L55). I will swallow the error message though as they are annoying and should not happen.

**Comment by KelSolaar** [comment]
So for the time being, if it bothers you and until I release a new version you can replace [this line](https://github.com/colour-science/colour-demosaicing/blob/develop/colour_demosaicing/__init__.py#L57):
 
```python
        ['git', 'describe'], cwd=os.path.dirname(__file__)).strip()
```

to

```python
        ['git', 'describe'], cwd=os.path.dirname(__file__), stderr=subprocess.STDOUT).strip()
```

It should swallow any error in that block.

**Comment by jewfro-cuban** [comment]
Great, Thanks.
