### ISSUE TITLE
Is "colour-demosaicing" available in Anaconda?

### ISSUE THREAD

**Issue by mrgransky** [colour-science/colour-demosaicing#15]
I would like to use `colour_demosaicing` in my python script as follows:
`from colour_demosaicing import demosaicing_CFA_Bayer_bilinear as demosaic`
I installed `colour-science` with  `conda install -c conda-forge colour-science` but I get the following error:

```
Traceback (most recent call last):
  File "robotcar.py", line 12, in <module>
    from colour_demosaicing import demosaicing_CFA_Bayer_bilinear as demosaic
ImportError: No module named colour_demosaicing
```
Is there any other package library I should install in conda env to import `colour_demosaicing` ?

**Comment by KelSolaar** [comment]
Hi @mrgransky,

You should actually install `colour-demosaicing`, `colour-science` is one of the base package required by `colour-demosaicing`.

Cheers,

Thomas

**Comment by mrgransky** [comment]
I can't find this package:
![anaconda](https://user-images.githubusercontent.com/11946010/83612258-d96b9e00-a58a-11ea-971d-0ddf4dd1b279.png)


I only find these packages in Anaconda:
![color_anaconda](https://user-images.githubusercontent.com/11946010/83612512-2bacbf00-a58b-11ea-8822-ca387d440d8d.png)

Is there something I am missing in here?
Cheers,

**Comment by KelSolaar** [comment]
Oh sorry, this one is not on Conda! Pip only!

**Comment by mrgransky** [comment]
is there any workaround for this ?
I can't use `pip install colour-demosaicing` cuz it's a univ computer and I don't have `sudo` priviledge!

**Comment by KelSolaar** [comment]
Oh, I see now! 

- If you have a Conda environment activated, you should not need admin rights and `pip install colour-demosaicing` should work
- Alternatively, you can try `pip install --user colour-demosaicing` and it will pull it down locally for your user
- Alternatively, you could simply pull down the repository and add it to `$PYTHONPATH`

**Comment by mrgransky** [comment]
tnx dude!
This is what I did as u suggested:

```
$ conda activate my_env
$ pip install colour-demosaicing
$ python
Python 2.7.17 |Anaconda, Inc.| (default, Oct 21 2019, 19:04:46) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from colour_demosaicing import demosaicing_CFA_Bayer_bilinear as demosaic
```
Appreciate ur help!

**Comment by KelSolaar** [comment]
Can you double-check that the package is effectively being installed in `my_env`, by the look of it, it seems that it is not the case!

**Comment by mrgransky** [comment]
let's say `my_env` is `py27_gpu` and I do the followings:
![conda](https://user-images.githubusercontent.com/11946010/83865560-05c01f80-a72f-11ea-965c-d23fd48290ec.png)

which says, I have installed `colour_demosaicing` from `pypi`! 
I can also successfully import `colour_demosaicing` from my python script!

**Comment by KelSolaar** [comment]
So it is working, right?

**Comment by mrgransky** [comment]
yes :+1:

**Comment by KelSolaar** [comment]
Glad to hear! :) Closing this one then!
