### ISSUE TITLE
How to save the image correctly?

### ISSUE THREAD

**Issue by yyuuliang** [colour-science/colour-demosaicing#18]
hi
thanks for this lib. I have a question about saving img.
I can use the plot to plot a correct color img, however, I don't know how to save it correctly. The color in the saved img is quite different from the plotting. Will you please show a example of img saving?

**Comment by KelSolaar** [comment]
Hi @yyuuliang,

So assuming you have an image:

```python
image = demosaicing_CFA_Bayer_Malvar2004(CFA)
```

It is float64 linear at this stage, so you could either save it as an EXR linear file:

```python
colour.write_image(image, 'my_image.exr')
```

or as a PNG file, but this would require non-linear encoding, e.g. sRGB:

```python
colour.write_image(colour.cctf_encoding(image), 'my_image.png')
```
