### ISSUE TITLE
Menon demosaicing optimization.

### ISSUE THREAD

**Issue by Zoldike** [colour-science/colour-demosaicing#2]
The convolutions can be optimized in the referenced code snippet. Two convolutions are sufficient using h0 + h1 as filter.
https://github.com/colour-science/colour-demosaicing/blob/develop/colour_demosaicing/bayer/demosaicing/menon2007.py#L113-L114

**Comment by KelSolaar** [comment]
@Zoldike: Thanks! I'm not sure I will update that anytime soon, feel free to open a PR if you need / want.

**Comment by Zoldike** [comment]
Actually, I don't have Python on my computer. I've just watched your code because it was more understandable than the reference implementation provided by the authors. :)
