### ISSUE TITLE
Demosaicing does not return clipped values

### ISSUE THREAD

**Issue by timmeinhardt** [colour-science/colour-demosaicing#3]
Demosaicing a normalized bayer image with float values between _0_ and _1_ using the _demosaicing_CFA_Bayer_Malvar2004_ method does not return a clipped image. This should either be mentioned in the documentation or demosaicing methods should finish with an appropriate clipping step since without noticing this behaviour the resulting PSNRs are significantly worse.

**Comment by KelSolaar** [comment]
That is a good point, at the moment none of the demosaicing definitions are clipping return values which is kind of consistent with everything we do for [Colour](https://github.com/colour-science/colour) or any related projects like this one.

The benefit in that particular case is that it allows for demosaicing HDR images: you merge the CFA bayer sensor data and then perform demosaicing as this [Jupyter Notebook](https://github.com/colour-science/colour-hdri/blob/develop/colour_hdri/examples/examples_merge_from_raw_files_with_post_demosaicing.ipynb) showcases it. If you were to clip the demosaiced output you would obviously lose all the dynamic range.

That being said I'll make a note in the definition.

Cheers,

Thomas

**Comment by timmeinhardt** [comment]
I did not know about the HDR application wich makes perfectly sense. A note in the documentation is totally fine then. This can be closed. Thanks for your fast response!

**Comment by KelSolaar** [comment]
You are welcome :)
