### ISSUE TITLE
Why is brightness changing when using the Malvar algorithm?

### ISSUE THREAD

**Issue by song4me** [colour-science/colour-demosaicing#33]
Hi,
When using the Malvar algorithm I get an output image which is much brighter than the original input image.
This change is different for different images. What is the reason this happens?

**Comment by KelSolaar** [comment]
Hi @song4me,

How are you reading the image? Is it a linear floating-point image in [0, 1] range?

Cheers,

Thomas

**Comment by song4me** [comment]
Hi Thomas,
Thanks for your quick reply.
I read the image using `colour.io.read_image` and indeed got a linear floating-point image in the range of [0, 1].
I disabled the `eotf_inverse_sRGB` function (which was causing some of the brightness change and is not needed for me), but there's still a slight change in colors which I can't trace.

Thanks,
Shirley

**Comment by KelSolaar** [comment]
Hello,

Would you have an example and/or the source image?

Cheers,

Thokas

**Comment by song4me** [comment]
Hi,
I'm attaching the input :
![in](https://user-images.githubusercontent.com/22259271/125608279-ec463b0a-8d41-4a12-9e43-49534f9b430d.png)
Result with opencv (for color comparison)
![dbyr_opencv](https://user-images.githubusercontent.com/22259271/125608341-47c6f078-54ed-429b-ba24-5c51820d62e2.png)
Results with Malvar from the colour demosaicing lib: 
![dbyr_malvar](https://user-images.githubusercontent.com/22259271/125608304-303fe41f-0509-42b1-8356-29baa7ffb03f.png)
thanks
