### ISSUE TITLE
Question regarding Cok (1987) "Constant Hue-Based Interpolation" method.

### ISSUE THREAD

**Issue by laihaotao** [colour-science/colour-demosaicing#5]
Hello, so glad to see your repo here, recently I also try to study demosaicing and I have a question about constant hue - based interpolation. If you have time, can you take a look [here](https://stackoverflow.com/questions/46859115/constant-hue-based-interpolation-opencv-python), thank you so much.

**Comment by KelSolaar** [comment]
Hi @laihaotao,

I don't think I will have any bandwidth to allocate for that unfortunately. Have you looked at the related patent: https://patentimages.storage.googleapis.com/pdfs/US4642678.pdf

Cheers,

Thomas

**Comment by laihaotao** [comment]
@KelSolaar Thanks for your reply, yes I have already read that patent. But anyway, I will try to figure it out.
