### ISSUE TITLE
The dev dependency `pytest-xdist` is always installed

### ISSUE THREAD

**Issue by gcolombeau** [colour-science/colour-demosaicing#55]
### Description

The dependency `pytest-xdist` is not listed in the extra `development` and is always installed since version 0.2.2. This brings even more dependencies not needed at runtime.

**Comment by KelSolaar** [comment]
Hi @gcolombeau,

Can you describe how you install the package as it is certainly an optional dependency as you can see here:

https://github.com/colour-science/colour-demosaicing/blob/develop/pyproject.toml#L75

and it is actually not even listed in the `setup.py` file (which is an error).

Cheers,

Thomas

**Comment by gcolombeau** [comment]
Well I don't install any extra, here is my minimal setup in a venv on Python 3.8:
```shell
$ pip install colour-demosaicing
$ pip show colour-demosaicing
Name: colour-demosaicing
Version: 0.2.2
Summary: CFA (Colour Filter Array) Demosaicing Algorithms for Python
Home-page: https://www.colour-science.org/
Author: Colour Developers
Author-email: colour-developers@colour-science.org
License: BSD-3-Clause
Location: /home/vboxdev/.virtualenvs/clean_venv/lib/python3.8/site-packages
Requires: colour-science, imageio, numpy, pytest-xdist, scipy, typing-extensions
Required-by:
```

I don't know how Poetry works or behaves so I can't really pinpoint why this happens. I only noticed this dependency wasn't added to [development](https://github.com/colour-science/colour-demosaicing/blob/develop/pyproject.toml#L108) when it was introduced but I'm not sure if this makes a difference.

**Comment by KelSolaar** [comment]
Thanks, this actually might be the reason, I updated the `pyproject.toml` file accordingly!

**Comment by KelSolaar** [comment]
Closing this one as it should have been resolved!
