### ISSUE TITLE
Sphinx documentation API section is empty.

### ISSUE THREAD

**Issue by jiawen** [colour-science/colour-demosaicing#6]
The primary README points an [API reference in Sphinx](https://colour-demosaicing.readthedocs.io/en/latest/api.html). However if one goes there, there is only a list of packages and modules, with no actual content. Is something missing?

**Comment by KelSolaar** [comment]
@jiawen! Thanks for letting me know, I'll check that ASAP.

**Comment by KelSolaar** [comment]
It should be fixed in the [develop](http://colour-demosaicing.readthedocs.io/en/develop/) branch of the documentation. Builds were broken since 613863da82bb096d7fef1059da632fcf3f9eb54e, took me a little while to figure out that.

Thanks!
